version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - aws cloudformation package --template-file lambdatemplate.yaml --s3-bucket photo-album-pipeline --output-template-file lambdaoutputtemplate.yaml
      - aws cloudformation deploy --template-file lambdaoutputtemplate.yaml --stack-name LambdaPipeline-stack --capabilities CAPABILITY_IAM
artifacts:
  type: zip
  files:
    - lambdatemplate.yaml
    - lambdaoutputtemplate.yaml